### ISSUE TITLE
summary parses $PROBLEM incorrectly

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbi#201]
[Original post](https://github.com/metrumresearchgroup/rbabylon/issues/296) from @callistosp on the rbabylon repo:

## Problem:
The model summary object contains information parsed from the model file stored in `run_details`. One of the variables under `run_details` is `$problem_text`, which appears to parse the $PROBLEM statement from the control stream.

The code currently parses the $PROBLEM statement incorrectly. "LEM" is appended to this value in a subset of models. I believe this is due to the regular expression parser grabs anything after "$PROB" from the control stream. However, users can use either $PROB or $PROBLEM for this chunk of code.

**Comment by callistosp** [comment]
oops, sorry @seth127 didn't realize this was a bbi issue

**Comment by seth127** [comment]
This has been lingering way too long. We just need to knock it out.

**Comment by callistosp** [comment]
this has been around so long I forgot I filed this issue
