### ISSUE TITLE
Batch Parameter Estimates

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbi#219]
# Summary

This function `bbi nonmem params` will provide an interface for reading in final parameter estimates from (the `.ext` files of) multiple models in batch.

# Specification

Can test on existing directory in `bbitest` repo: https://github.com/metrumresearchgroup/bbitest/tree/master/testdata/bbi_summary

* User can pass a directory and look for an `.ext` file corresponding to each `.ctl` file in that directory
  * For example, if the dir contains `100.ctl` we will look for `100/100.ext`
* If failure that row should return the reason (some subset of possible error messages) and all params should be `NA` for that row
  * No `-10000000` line from a given `.ext` file (will need an example added to `bbitest`)
  * No `.ext` file at the expected path ([1001](https://github.com/metrumresearchgroup/bbitest/blob/master/testdata/bbi_summary/1001/1001.1.TXT))
  * `.ext` file at expected path is empty or unreadable (will need an example added to `bbitest`)
* If differing numbers of params in different models, param names will be reconciled in the header and there will `NA` in the relevant columns for the rows that do not have that parameter. (`bbitest` dir above will test this)
* If more than 1 estimation method, take estimates from final estimation method ([example2_itsimp](https://github.com/metrumresearchgroup/bbitest/blob/master/testdata/bbi_summary/example2_itsimp/example2_itsimp.ext))

**Comment by kyleam** [comment]
Covered by #253 (which superseded the linked PR, #202).
