### ISSUE TITLE
Bad import of `number_of_data_records` when using $INFN?

### ISSUE THREAD

**Issue by dpolhamus** [metrumresearchgroup/bbi#227]
I'm not sure exactly where the problem is here, but when generating a `model_summary` of a model in which I've used `$INFN` to subset the dataset (i.e., instead of `IGNORE` in `$DATA`) it seems like `nonmem_summary` sets `number_of_data_records` to a large negative number (-999999999).  

The lst file reports the correct number of records (after subsetting).

Here's example offending `$INFN`, in this case keeping records in which ANL01FL==1:

```
$INFN
  IF(PRED_IGNORE_DATA_TEST==1) THEN
    PRED_IGNORE_DATA=0
    IF(ANL01FL.NE.1) PRED_IGNORE_DATA=1
    RETURN;
  ENDIF
```

**Comment by kyleam** [comment]
The -999999999 is coming from bbi:

https://github.com/metrumresearchgroup/bbi/blob/43f1495bf78e6a6f41043889c76d8068cfe70e4c/parsers/nmparser/structs.go#L184

It initializes `RunDetails` with this value.  `ParseRunDetails` will try to set `runDetails.NumberOfDataRecords` from the "NO. OF DATA RECS IN DATA SET" line in the lst file:

https://github.com/metrumresearchgroup/bbi/blob/43f1495bf78e6a6f41043889c76d8068cfe70e4c/parsers/nmparser/parse_run_details.go#L84-L85

Just as a test, if I drop that line from bbr's `inst/model/nonmem/basic/1/1.lst`, I see the placeholder value:

```
$ bbi nonmem summary --json inst/model/nonmem/basic/1/1 | jq .run_details.number_of_data_records
799
# <drop "NO. OF DATA ..." line>
$ bbi nonmem summary --json inst/model/nonmem/basic/1/1 | jq .run_details.number_of_data_records
-999999999
```

> The lst file reports the correct number of records (after subsetting).

Hmm, so if it's there, then `ParseRunDetails` should be able to extract it. @dpolhamus, does the line in the lst file look slightly different when `$INFN` is used?

**Comment by dpolhamus** [comment]
Here's an excerpt from an `lst` with a `$INFN` block:

```
0FORMAT FOR DATA:
 (22(3E21.0/))

 TOT. NO. OF DATA RECS:      1707
 TOT. NO. OF OBS RECS:      190
 TOT. NO. OF INDIVIDUALS:      205
0LENGTH OF THETA:   5
```

**Comment by kyleam** [comment]
Thanks.  I've proposed a fix in gh-228.

That fix assumes it's okay to just fall back to the "TOT. NO. OF DATA RECS" value.  Do you think that value is always a reasonable substitute?  And is it valid to expect only one "TOT. NO. OF DATA RECS" in the output?

**Comment by dpolhamus** [comment]
Seems reasonable to me to fall back to value; at least, until ICON/NONMEM decides to change it slightly again.
But yes, I would only ever expect one recording of the data records per lst. 

Thanks @kyleam!
