### ISSUE TITLE
make E2E tests run faster 

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbi#233]
* run less scenarios
  * ~~maybe move some scenarios to be unit tests that use the mocked grid~~
* reconfigure drone server to keep up a tiny worker node at all

**As we go**
* tighten up (and document, as necessary) skipping mechanism for both long and grid tests so that we can run the bbi test suite locally, but skip these tests 
* add Test Id's for mrgvalidate

**Comment by seth127** [comment]
This is mostly done. Going to do a few quick tweaks to cut down unnecessary scenarios and then we're good.

* long-running one where we verify the extension of models should _only_ run on the expansion test
* post-execution test only needs one scenario (acop)
* NMqual test only needs one scenario (acop)

**Comment by shairozan** [comment]
* Restructured tests
* Cut out unnecessary scenarios
* Forced one worker to exist at all times
