### ISSUE TITLE
move tests from bbitest to bbi 

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbi#235]
* move all of [these tests](https://github.com/metrumresearchgroup/bbitest)
* move [relevant test data](https://github.com/metrumresearchgroup/bbitest/tree/master/testdata)
* change [drone](https://github.com/metrumresearchgroup/bbi/blob/develop/.drone.yml) to call new tests and not call bbitest
* delete bbitest repo

**Comment by elisarver** [comment]
This is completed/merged
