### ISSUE TITLE
bbi_binary from YAML controls only SGE execution

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbi#261]
I initially thought this was a bug, but I realize it's really just an obscure feature. That said, this issue is essentially a discussion about whether we should change this behavior.

# Summary 

The `bbi_binary` field in the `bbi.yaml` file allows the user to specify a _different installation_ of `bbi` (i.e. different than the one used in the original command) to be written in the `grid.sh` file (code [here](https://github.com/metrumresearchgroup/bbi/blob/develop/cmd/sge.go#L378-L382)) which is actually executed on the worker node in the grid.

I propose getting rid of this field for the following reasons:

1. It hinders shareability because a user may attempt to run a model (on the grid) using a `bbi.yaml` created by a different user (a collaborator, or previous scientist on a project) and the `bbi_binary` may point to a path that doesn't exist on the current user's system. (This situation is what surfaced this discussion.)
2. It is not clear when you would need, or even want, this capability. Why not just call the original command with the installation of `bbi` that you want the grid to use?
3. It is confusing for a `bbr` user who thinks of `options(bbr.bbi_exe_path)` as their mechanism for setting which installation of `bbi` to use. Currently, this _actually_ sets the installation to use for local execution, and for calling the bbi command, but _not_ for grid execution. This seems unnecessarily complex and likely to confuse.

# Proposed change

The proposal is to execute on the grid with the same executable that was called. This will likely be done by writing the path to the executable used to trigger the command to the `grid.sh` file. 

In order to be backwards-compatible I'd propose:
* Change `bbi init` to _not_ write out the `bbi_binary` field
* If `bbi` finds `bbi_binary` in the input config, respect it and revert to legacy behavior. Otherwise, set to path of executable that called the command.

This way any users who are relying on this behavior in existing `bbi.yaml` files will not be effected, but users who have an issue with an existing `bbi.yaml` can simply delete the `bbi_binary` field.

**Comment by kylebaron** [comment]
This seems reasonable I think.
