### ISSUE TITLE
Set maxlim by default

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/bbi#262]
- Default value set to 2
- When maxlim is 3 we should also pass `-prcompile`; this will _force_ recompilation of some model components 
  - maxlim 3 is needed when we need more than default number of records per individual; if this is needed, it is usually in simulation context

**Comment by kyleam** [comment]
gh-279 handles the `-maxlim=2` default change.

> when maxlim is 3 we should also pass -prcompile

I didn't take care of that there, so let's open a dedicated issue if you feel strongly about that one.  My main concern is it sounds to me like `-maxlim=3` shouldn't unconditionally imply `-prcompile`.  The nmfe help says:

```
With maxlim=3, it is preferred to also use -tprdefault, or -prcompile,
but not -prdefault, as NMTRAN's optional resizing of  the  PREDPP
size parameter MAXRECID may conflict with the -prdefault option
```

So, the user may want to pass `-prcompile` or `-tprdefault`, and at that point, it seems better to me to not bbi-specific logic to the mix and instead say "if a caller is setting -maxlim=3, then they should know to specify either -prcompile or -tprdefault (both exposed by bbi)".

**Comment by kylebaron** [comment]
@seth127 @kyleam https://github.com/metrumresearchgroup/bbr/blob/f49748b8499cd157aca35a80b6acb3af0fbb4ae5/R/aaa.R#L26

**Comment by kyleam** [comment]
> @seth127 @kyleam https://github.com/metrumresearchgroup/bbr/blob/f49748b8499cd157aca35a80b6acb3af0fbb4ae5/R/aaa.R#L26

Thanks!  Will adjust. (I was planning to review `print_bbi_args()` due to gh-280, so hopefully I would have caught this too)
