### ISSUE TITLE
Automatically clean up FDATA.csv whenever FDATA is cleaned up

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/bbi#269]
# Summary 
As a user, I want bbi to treat `FDATA.csv` the same way it treats `FDATA` when cleaning up files post-run

> With NONMEM 7.5, an additional file, FDATA.csv is  produced  that
outputs  the contents of its input data file (typically FDATA) in
a comma delimited file format, so you can check how NONMEM inter-
prets  the  input data.

**Comment by kyleam** [comment]
Thanks @kylebaron

The core code change may just be (untested):

```diff
diff --git a/cmd/nonmem.go b/cmd/nonmem.go
index a416650..249adca 100644
--- a/cmd/nonmem.go
+++ b/cmd/nonmem.go
@@ -76,6 +76,7 @@ var nonMemTemporaryFiles []string = []string{
 	"compile.lnk",
 	"FCON",
 	"FDATA",
+	"FDATA.csv",
 	"FMSG",
 	"FREPORT",
 	"FSIZES",
diff --git a/runner/consts.go b/runner/consts.go
index edd1e52..166690b 100644
--- a/runner/consts.go
+++ b/runner/consts.go
@@ -14,6 +14,7 @@ func EstOutputFileCleanLevels(r string) map[string]int {
 	EstOutputFiles["compile.lnk"] = 1
 	EstOutputFiles["FCON"] = 1
 	EstOutputFiles["FDATA"] = 1
+	EstOutputFiles["FDATA.csv"] = 1
 	EstOutputFiles["FMSG"] = 1
 	EstOutputFiles["FREPORT"] = 1
 	EstOutputFiles["FSIZES"] = 1
```

I haven't looked closely at the testing situation yet, but an additional aspect is that right now drone is only testing with `NMVERSION: nm74gf`

**Comment by kylebaron** [comment]
@kyleam Seems reasonable; I searched the code a bit to make sure this is where stuff was happening and ran across this too, but don't know the code enough (at all) to know if it would be any other place. But I feel like following whatever we do with `FDATA`  and clean level should work.  

Good point on NONMEM version; should only see this appearing with 75.  Would be good investment to switch to nm75 as lots of new stuff there and most projects should be using this version going forward.

**Comment by dpastoor** [comment]
Yep that should do it
