### ISSUE TITLE
Original datafile to model directory

### ISSUE THREAD

**Issue by Mutaz94** [metrumresearchgroup/bbi#275]
Hi @seth127:

When one handle simulation-estimation, it would be convenient to copy the original dataset to the model directory (other than FDATA). Is there any similar functionality to do so? e.g. if data `data.csv` is in `data\` folder, when the model executed, a copy of `data.csv` would go to the model dir. Thanks!!

**Comment by kyleam** [comment]
> it would be convenient to copy the original dataset to the model directory (other than FDATA). Is there any similar functionality to do so?

I'm not Seth, but not that I'm aware of.  Can you say a bit more about why you would find that convenient?

Depending on the answer, perhaps you'd find bbr's [`nm_data()`](https://metrumresearchgroup.github.io/bbr/reference/nm_file.html) or [`nm_join()`](https://metrumresearchgroup.github.io/bbr/reference/nm_join.html) useful.

**Comment by Mutaz94** [comment]
Hey Kyle,

Thanks for your response. When dealing with simulation-estimation a lot of data generated for different scenarios (like bootstrap) and would be convenient to place each data with associated model. It was pointed out to me today that with project example, for bootstrap, is to create a subdir inside model directory but was curious if there any functionality to held the data there. I will check out these functions. Thanks a lot!!

**Comment by seth127** [comment]
Hi Mutaz. This may be what you're referencing, but our example script [here](https://github.com/metrumresearchgroup/expo1-nonmem-foce/blob/main/script/boot-generate.R#L25-L28) puts the bootstrap data in a subdirectory under `data/boot/` and keeps the models in `model/pk/boot/`. Let us know if there are reasons this isn't ideal. 

We've considered creating some bootstrap helpers in `bbr` (probably based on what's in that script I linked ^) but haven't done it yet. Definitely on the roadmap though.

**Comment by Mutaz94** [comment]
It is great way to handle and keep data consistent. I was curious if there a way to through a copy of original data into the model dir for example if a control stream called `1.mod` a copy of data will reside in `../1/org.dta`. Anyway, I'm now comfortable with the way you guys provided in expo project.
