### ISSUE TITLE
Exit Code 107 when submitting model

### ISSUE THREAD

**Issue by poonv** [metrumresearchgroup/bbi#313]
Had an issue submitting a nonmem model on windows 10 (R: 4.3.1, Rstudio: 2023.09, bbi version: 3.2.2) where the execution would stop due an exit code 107. Did also try running `Sys.unsetenv("GFORTRAN_STDOUT_UNIT")` first but didn't seem to work.

**Error in check_status_code(p$get_exit_status(), output, .cmd_args) : 
`bbi nonmem run local C:/Users/user1/nm/run004.ctl --overwrite` returned status code 1 -- STDOUT and STDERR: 
time="2023-10-11T14:38:20-07:00" level=info msg="Successfully loaded default configuration from C:\\Users\\user1\\nm\\bbi.yaml"
time="2023-10-11T14:38:20-07:00" level=info msg="Beginning Local Path"
time="2023-10-11T14:38:20-07:00" level=info msg="A total of 1 models have completed the initial preparation phase"
time="2023-10-11T14:38:20-07:00" level=info msg="[run004] Beginning local work phase"
time="2023-10-11T14:38:21-07:00" level=error msg="[run004] Exit code was 107, details were exit status 107"
time="2023-10-11T14:38:21-07:00" level=error msg="[run004] output details were: Starting NMTRAN\r\n  \r\n WARNINGS AND ERRORS (IF ANY) FOR PROBLEM    1\r\n             \r\n (WARNING  2) NM-TRAN INFERS THAT THE DATA ARE POPULATION.\r\n             \r\n (WARNING  13) WITH USER-WRITTEN PRED OR $PRED,**

**Comment by seth127** [comment]
Assuming this model is proprietary, it may be tough to get reproducer, though I agree with @kyleam that would greatly increase our chances of figuring out what's going on here. @poonv if you are able to share a model, much appreciated, but if not that's fine.

It looks to me like the error message is truncated here (ends in a comma, no closed quote)

```
level=error msg="[run004] output details were: Starting NMTRAN\r\n \r\n WARNINGS AND ERRORS (IF ANY) FOR PROBLEM 1\r\n \r\n (WARNING 2) NM-TRAN INFERS THAT THE DATA ARE POPULATION.\r\n \r\n (WARNING 13) WITH USER-WRITTEN PRED OR $PRED,
```

My bet is that the useful part of the error is below. @poonv could you take a look in the `<model>.ctl.out` file in your model output directory directory? You should be able to get the path with `bbr::build_path_from_model(..., ".ctl.out")`. If you can find the full error in there, please paste that into the issue. Thanks.

**Comment by poonv** [comment]
@seth127 Thanks for the help! I was able to find the output file with the full error description there. Turns out it was just simple dataset pointer issue.

**Comment by kyleam** [comment]
@poonv Thanks for reporting back.  I've opened a dedicated issue about the truncated output (gh-314).
